name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Kubernetes
      run: |
        # Add your deployment commands here
        # For example, using Helm:
        helm upgrade --install my-app ./helm-charts/my-app
